server:
  host: "0.0.0.0"
  port: 8080
  mode: "debug"
  read_timeout: 30s
  write_timeout: 30s

database:
  type: "sqlite"
  path: "./data/authenticator.db"
  max_connections: 25
  max_retries: 3
  retry_delay: 5s

security:
  rate_limit_requests: 100
  rate_limit_window: "1m"
  require_strong_auth: true
  session_timeout: "24h"
  force_secure_secrets: true
  max_login_attempts: 5
  lockout_duration: "15m"

totp:
  default_period: 30
  default_digits: 6
  key_rotation_interval: "24h"
  backup_key_retention: "48h"
  require_signature: true
  max_clock_skew: "30s"

business:
  webhook_timeout: "10s"
  analytics_retention: "90d"
  max_integrations: 10
  require_whitelist: false

logging:
  level: "info"
  format: "json"
  output: "stdout"
  audit_level: "info"
  max_file_size: "100MB"

cors:
  allowed_origins: []
  allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowed_headers: ["Content-Type", "Authorization", "X-API-Key"]
  expose_headers: ["X-Total-Count"]
  allow_credentials: true
  max_age: 3600